### ISSUE TITLE
bug in save_file()

### ISSUE THREAD

**Issue by roblanf** [roblanf/MixtureModelHMM#12]
with the example on the readme:

```
save_file(hmm_result = hmm_result, output_filename = "hmm_output")
```

When I try to open the file, I get:
![Screen Shot 2022-06-10 at 12 45 54 pm](https://user-images.githubusercontent.com/895251/172980141-911f6048-0c70-435a-87bf-e19f8c6eb8fd.jpg)

**Comment by rahilvora9** [comment]
removed save_file() function
https://github.com/roblanf/MixtureModelHMM/commit/2c82da17b7499e98d7af2c6d182049688e701d56
