### ISSUE TITLE
add the scatter plot into the hmm_result

### ISSUE THREAD

**Issue by roblanf** [roblanf/MixtureModelHMM#15]
include an option in `run_HMM()` for `include_scatter_plot = TRUE`, so that folks with big datasets can choose not to include it.

**Comment by rahilvora9** [comment]
Do we want to scatter-plot on the same input file user provided(.sitelh or .siteprob)? or we can force it to be .siteprob replacing the extension of the file as long as file exists in the same folder.

**Comment by rahilvora9** [comment]
Also, the scatter plot only be start plotting after `hmm_result$initial_scatter_plot` is called as I can set it as a function call, so we might not need include_scatter_plot = TRUE/FALSE
https://github.com/roblanf/MixtureModelHMM/commit/79eb53f40a324bc020a05f220ca94dbcc47feda5

**Comment by rahilvora9** [comment]
https://github.com/roblanf/MixtureModelHMM/commit/c82d249bb50a128a6fefa551b5a8916f4d53cee5
