### ISSUE TITLE
error on library(MixtreModelHMM)

### ISSUE THREAD

**Issue by roblanf** [roblanf/MixtureModelHMM#17]
```
> library(MixtureModelHMM)
Error: package or namespace load failed for ‘MixtureModelHMM’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘lifecycle’ 1.0.0 is already loaded, but >= 1.0.1 is required
```

**Comment by roblanf** [comment]
this was directly after re-installing from github

**Comment by roblanf** [comment]
it goes away if I

```
install.packages("lifecycle")
```

but it should be addressed before we publish!

**Comment by rahilvora9** [comment]
https://github.com/roblanf/MixtureModelHMM/commit/802389018d1dc6599a9bbb82ce78df18536d5086
I introduced tidyverse as dependency so it should be fine

**Comment by rahilvora9** [comment]
I did a fresh install but could not see the error
