### ISSUE TITLE
error in save_report: template 'HMM_report' was not found in the MixtureModelHMM package

### ISSUE THREAD

**Issue by jeremiasivan** [roblanf/MixtureModelHMM#20]
File (`run_hmm.R`):
```
library("MixtureModelHMM")
hmm_result <- run_HMM(site_info = "../chr21.sitelh", aln_info = "../chr21.alninfo")
save_report(hmm_result = hmm_result, output_filename = "hmm_report.Rmd")
```

Command: `nohup Rscript run_hmm.R > nohup.txt&`

Output
```
[1] "# Loading input files"
[1] "# Initialising HMM"
[1] "Model 4 - 3 additional emission for constant site, non-informative sites and same parsimony"
[1] "The probability of these addtional emissions is equal for all classes"
[1] "Sites emitted from each class"
seq
    E1    E10     E2     E3     E4     E5     E6     E7     E8     E9 
   510 178363   3288  10911  11272   5730   6150   1769   7274 775493 
[1] "# Training HMM"
[1] "# Running viterbi algorithm"
[1] "# Making alignment plot"
[1] "# Making scatter plot"
Warning message:
WARNING: Your input file is large, and making the scatterplot might take a long time. 
Error in draft(output_filename, template = "HMM_report", package = "MixtureModelHMM") : 
  The template 'HMM_report' was not found in the MixtureModelHMM package
Calls: save_report -> draft
Execution halted
```

Is this a bug, or did I do something wrong?

**Comment by roblanf** [comment]
@rahilvora9 do you have any idea about this one? This is on linux, not repeated on a mac.

**Comment by rahilvora9** [comment]
Hi @jeremiasivan,

I could not replicate on my mac/Rstudio but I found out the template name in my draft() function was 'HMM_report' while template I created(located in 'inst/rmarkdown/templates') is named 'hmm_report' so may be linux or your particular version of R is case sensitive for this template name, I have made renamed 
```draft(output_filename, template = "HMM_report", package = "MixtureModelHMM")```
to
```draft(output_filename, template = "hmm_report", package = "MixtureModelHMM")```
Could you try to run again?

**Comment by jeremiasivan** [comment]
Hi @rahilvora9 - Yes, it is working properly now. Thanks!
